In [74]:
import numpy as np
import os
import torch

In [160]:
import paths
import config
import util
import importlib
import data

In [161]:
reload_packages = [paths, util, config, data]
for package in reload_packages:
    importlib.reload(package)
# importlib.reload(data)

# Load Data

In [162]:
data = data.Data()

In [163]:
train_loader = data.get_loader(mode='train')
val_loader = data.get_loader(mode='val')
test_loader = data.get_loader(mode='test')

Preparing corpus...
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
Fa

- [x] Encoder with pBLSTM
- [ ] Decoder with attention
- [ ] Run with ctc decoder package

In [165]:
test = torch.rand((2,4,6))

In [166]:
test

tensor([[[0.6955, 0.3495, 0.6494, 0.0398, 0.6244, 0.6296],
         [0.3934, 0.5853, 0.2519, 0.6088, 0.6838, 0.9398],
         [0.2320, 0.8889, 0.6165, 0.8721, 0.9293, 0.1492],
         [0.9164, 0.2679, 0.8323, 0.3445, 0.0937, 0.2521]],

        [[0.0844, 0.8881, 0.0815, 0.3233, 0.5118, 0.9274],
         [0.5324, 0.6198, 0.4622, 0.6387, 0.2578, 0.2945],
         [0.9677, 0.9266, 0.4383, 0.2945, 0.6129, 0.2483],
         [0.2953, 0.7952, 0.3841, 0.1417, 0.9776, 0.4281]]])

In [168]:
test.view(2, int(4//2), 6*2)

tensor([[[0.6955, 0.3495, 0.6494, 0.0398, 0.6244, 0.6296, 0.3934, 0.5853,
          0.2519, 0.6088, 0.6838, 0.9398],
         [0.2320, 0.8889, 0.6165, 0.8721, 0.9293, 0.1492, 0.9164, 0.2679,
          0.8323, 0.3445, 0.0937, 0.2521]],

        [[0.0844, 0.8881, 0.0815, 0.3233, 0.5118, 0.9274, 0.5324, 0.6198,
          0.4622, 0.6387, 0.2578, 0.2945],
         [0.9677, 0.9266, 0.4383, 0.2945, 0.6129, 0.2483, 0.2953, 0.7952,
          0.3841, 0.1417, 0.9776, 0.4281]]])

In [169]:
test.contiguous().view(2, int(4//2), 6*2)

tensor([[[0.6955, 0.3495, 0.6494, 0.0398, 0.6244, 0.6296, 0.3934, 0.5853,
          0.2519, 0.6088, 0.6838, 0.9398],
         [0.2320, 0.8889, 0.6165, 0.8721, 0.9293, 0.1492, 0.9164, 0.2679,
          0.8323, 0.3445, 0.0937, 0.2521]],

        [[0.0844, 0.8881, 0.0815, 0.3233, 0.5118, 0.9274, 0.5324, 0.6198,
          0.4622, 0.6387, 0.2578, 0.2945],
         [0.9677, 0.9266, 0.4383, 0.2945, 0.6129, 0.2483, 0.2953, 0.7952,
          0.3841, 0.1417, 0.9776, 0.4281]]])