In [ ]:
import numpy as np
import torch

In [165]:
test = torch.rand((2,4,6))

In [166]:
test

tensor([[[0.6955, 0.3495, 0.6494, 0.0398, 0.6244, 0.6296],
         [0.3934, 0.5853, 0.2519, 0.6088, 0.6838, 0.9398],
         [0.2320, 0.8889, 0.6165, 0.8721, 0.9293, 0.1492],
         [0.9164, 0.2679, 0.8323, 0.3445, 0.0937, 0.2521]],

        [[0.0844, 0.8881, 0.0815, 0.3233, 0.5118, 0.9274],
         [0.5324, 0.6198, 0.4622, 0.6387, 0.2578, 0.2945],
         [0.9677, 0.9266, 0.4383, 0.2945, 0.6129, 0.2483],
         [0.2953, 0.7952, 0.3841, 0.1417, 0.9776, 0.4281]]])

In [168]:
test.view(2, int(4//2), 6*2)

tensor([[[0.6955, 0.3495, 0.6494, 0.0398, 0.6244, 0.6296, 0.3934, 0.5853,
          0.2519, 0.6088, 0.6838, 0.9398],
         [0.2320, 0.8889, 0.6165, 0.8721, 0.9293, 0.1492, 0.9164, 0.2679,
          0.8323, 0.3445, 0.0937, 0.2521]],

        [[0.0844, 0.8881, 0.0815, 0.3233, 0.5118, 0.9274, 0.5324, 0.6198,
          0.4622, 0.6387, 0.2578, 0.2945],
         [0.9677, 0.9266, 0.4383, 0.2945, 0.6129, 0.2483, 0.2953, 0.7952,
          0.3841, 0.1417, 0.9776, 0.4281]]])

In [169]:
test.contiguous().view(2, int(4//2), 6*2)

tensor([[[0.6955, 0.3495, 0.6494, 0.0398, 0.6244, 0.6296, 0.3934, 0.5853,
          0.2519, 0.6088, 0.6838, 0.9398],
         [0.2320, 0.8889, 0.6165, 0.8721, 0.9293, 0.1492, 0.9164, 0.2679,
          0.8323, 0.3445, 0.0937, 0.2521]],

        [[0.0844, 0.8881, 0.0815, 0.3233, 0.5118, 0.9274, 0.5324, 0.6198,
          0.4622, 0.6387, 0.2578, 0.2945],
         [0.9677, 0.9266, 0.4383, 0.2945, 0.6129, 0.2483, 0.2953, 0.7952,
          0.3841, 0.1417, 0.9776, 0.4281]]])

In [28]:
from torch.nn.utils.rnn import pad_sequence,pack_padded_sequence,pad_packed_sequence


In [2]:
test = torch.randint(0,10,(2,3,4))

In [3]:
test

tensor([[[8, 0, 4, 2],
         [6, 8, 3, 8],
         [7, 3, 3, 9]],

        [[2, 7, 7, 4],
         [3, 7, 2, 7],
         [9, 1, 9, 5]]])

In [14]:
test1 = test.new_zeros(2,4)

In [19]:
torch.cat([test[:,1,:], test1], dim=1)

tensor([[6, 8, 3, 8, 0, 0, 0, 0],
        [3, 7, 2, 7, 0, 0, 0, 0]])

In [18]:
test[:,1,:].unsqueeze(1)

tensor([[[6, 8, 3, 8]],

        [[3, 7, 2, 7]]])

In [21]:
test[-1].size()

torch.Size([3, 4])

In [22]:
test

tensor([[[8, 0, 4, 2],
         [6, 8, 3, 8],
         [7, 3, 3, 9]],

        [[2, 7, 7, 4],
         [3, 7, 2, 7],
         [9, 1, 9, 5]]])

In [59]:
test = torch.randint(0,10,(1,10))
test
# batch_size, max_length

tensor([[4, 7, 2, 2, 2, 7, 6, 9, 9, 1]])

In [66]:
test1 = torch.stack([torch.arange(0,10) for i in range(3)]).int()# batch_size = 3, max_len = 10
test1

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=torch.int32)

In [73]:
test2 = torch.stack([torch.full((1,10),i).squeeze(0) for i in torch.tensor([7,8,9])]).int()
test2.size()

torch.Size([3, 10])

In [75]:
mask = test1<test2

In [169]:
mask

tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]], dtype=torch.uint8)

In [171]:
mask.unsqueeze(2).repeat(
            (1, 1, 6)).size()

torch.Size([3, 10, 6])

In [117]:
test[0,:,0].sum()

tensor(1.0000)

In [124]:
mask.unsqueeze(1).repeat((1,5,1)).size()

torch.Size([3, 5, 10])

In [134]:
test = torch.mul(mask.unsqueeze(2).repeat((1,1,5)).float(),torch.randint(1,10,(3,10,5)).float())

In [164]:
test[:,:,1].unsqueeze(2)/test[:,:,1].unsqueeze(2).sum(dim=1, keepdim=True)

tensor([[[0.0588],
         [0.1471],
         [0.2647],
         [0.0588],
         [0.2647],
         [0.1471],
         [0.0588],
         [0.0000],
         [0.0000],
         [0.0000]],

        [[0.1837],
         [0.0816],
         [0.0204],
         [0.1633],
         [0.1224],
         [0.1020],
         [0.1429],
         [0.1837],
         [0.0000],
         [0.0000]],

        [[0.0741],
         [0.1481],
         [0.1111],
         [0.1111],
         [0.1296],
         [0.0556],
         [0.1667],
         [0.0741],
         [0.1296],
         [0.0000]]])

In [166]:
torch.cat((torch.randint(0,10,(3,1,2)), torch.randint(0,10,(3,1,2))), dim=1)

tensor([[[9, 7],
         [0, 1]],

        [[6, 9],
         [2, 1]],

        [[8, 2],
         [7, 5]]])

In [168]:
torch.randint(0,10,(3,2)).unsqueeze(1).size()

torch.Size([3, 1, 2])

In [176]:
test[:,:,0]

tensor([[9., 6., 2., 8., 7., 5., 7., 0., 0., 0.],
        [5., 1., 8., 2., 6., 3., 9., 8., 0., 0.],
        [5., 9., 2., 1., 6., 2., 4., 8., 2., 0.]])

In [191]:
mask = torch.stack([torch.arange(0,10) for i in range(5)]).int()

In [192]:
mask

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=torch.int32)

In [193]:
test = torch.stack([torch.full((1,10),i).squeeze(0) for i in torch.tensor([7,8,9,7,2])]).int()

In [194]:
mask < test

tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=torch.uint8)